query show($id: ID!) {
	show(id: $id) {
		id
		startTime
		durationInSeconds
		pricing {
			screenSeatCategory {
				id
			}
			price
			mrp
			discount
			tax
		}
		movie {
			id
		}
		screen {
			id
		}
		vendor {
			id
		}
		store {
			id
			name
			email
		}
		createdAt
		updatedAt
	}
}
